force-app/main/default/objects/agent__c/agent__c.object-meta.xml
<CustomObject>
    <description>Project -- Insurance project
Object Info -- agent registration purpose</description>
    <label>agent</label>
    <nameField>
        <displayFormat>AGID-{0000}</displayFormat>
        <label>Agent Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/agent__c/fields/Agent_Name__c.field-meta.xml
<CustomField>
    <fullName>Agent_Name__c</fullName>
    <label>Agent Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Life_Insurence__c/Life_Insurence__c.object-meta.xml
<CustomObject>
    <label>Life Insurence</label>
    <nameField>
        <displayFormat>LIID-{0000}</displayFormat>
        <label>PolicyId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Life Insurences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Life_Insurence__c/fields/agent_ID__c.field-meta.xml
<CustomField>
    <fullName>agent_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>agent ID</label>
    <referenceTo>agent__c</referenceTo>
    <relationshipLabel>Life Insurences</relationshipLabel>
    <relationshipName>Life_Insurences</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Life_Insurence__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <formula>Premium_End_Date__c -10</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Life_Insurence__c/fields/No_Of_Terms__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Terms__c</fullName>
    <label>No.Of Terms</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Life_Insurence__c/fields/Policy_Holder__c.field-meta.xml
<CustomField>
    <fullName>Policy_Holder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Policy Holder Name</label>
    <referenceTo>Policy_Holder__c</referenceTo>
    <relationshipLabel>Life Insurences</relationshipLabel>
    <relationshipName>Life_Insurences</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Life_Insurence__c/fields/PremiumAmount__c.field-meta.xml
<CustomField>
    <fullName>PremiumAmount__c</fullName>
    <label>PremiumAmount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Motor_Insurence__c/Motor_Insurence__c.object-meta.xml
<CustomObject>
    <label>Motor Insurence</label>
    <nameField>
        <displayFormat>MIID-{0000}</displayFormat>
        <label>PolicyID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Motor Insurences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Motor_Insurence__c/fields/agent_ID__c.field-meta.xml
<CustomField>
    <fullName>agent_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>agent ID</label>
    <referenceTo>agent__c</referenceTo>
    <relationshipLabel>Motor Insurences</relationshipLabel>
    <relationshipName>Motor_Insurences</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Motor_Insurence__c/fields/NO_Of_Terms__c.field-meta.xml
<CustomField>
    <fullName>NO_Of_Terms__c</fullName>
    <label>NO.Of Terms</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Motor_Insurence__c/fields/Policy_Holder__c.field-meta.xml
<CustomField>
    <fullName>Policy_Holder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Policy Holder</label>
    <referenceTo>Policy_Holder__c</referenceTo>
    <relationshipLabel>Motor Insurences</relationshipLabel>
    <relationshipName>Motor_Insurences</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy_Holder__c/Policy_Holder__c.object-meta.xml
<CustomObject>
    <label>Policy Holder</label>
    <nameField>
        <label>Policy Holder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policy Holders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy_Holder__c/fields/Ph_Id__c.field-meta.xml
<CustomField>
    <fullName>Ph_Id__c</fullName>
    <displayFormat>PHID-{0000}</displayFormat>
    <label>Ph Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/homeclass.cls
public with sharing class homeclass {
   
   //------------------------------------
    @AuraEnabled(cacheable=true)
    public static List<agent__c> getAgentList(){
        try{
        List<agent__c>Agent=new List<agent__c>();
             Agent= [select Name,Agent_Name__c,Email__c,Phone__c from agent__c ];
             return Agent;
            
        } catch(Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    //---------------------------------------

    @AuraEnabled(cacheable=true)
    public static List<Policy_Holder__c> getPolicyHolderList(){
        try{
        List<Policy_Holder__c>Policy=new List<Policy_Holder__c>();
                 Policy=[SELECT Ph_Id__c,Name,Email__c,Phone__c FROM Policy_Holder__c ];
                 return Policy;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    //------------------------------------------
    @AuraEnabled
    public static List<Life_Insurence__c> getLifeInsurenceList(){
        try{
        List<Life_Insurence__c>Life=new List<Life_Insurence__c>();
             Life=[SELECT Name,Policy_Holder__c,No_Of_Terms__c,agent_ID__c FROM Life_Insurence__c];
             return Life;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    //---------------------------------------------
    @AuraEnabled
    public static List<Motor_Insurence__c> getMoterInsurenceList(){
        try{
        List<Motor_Insurence__c>moter=new List<Motor_Insurence__c>();

        moter=[SELECT Name,Policy_Holder__c,NO_Of_Terms__c,Premium_Amount__c FROM Motor_Insurence__c];
        return moter;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled(cacheable=true)
    public static agent__c  myAgent(){
        try {
            
            agent__c c= [select Name,Agent_Name__c,Email__c,Phone__c, DOB__c,Gender__c FROM agent__c  limit 1];
            return c;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }  
    //-----------------------------------------------------------------------------
    @AuraEnabled(cacheable=true)
    public static List<Life_Insurence__c> lifeData(id data){
        try {
            return [select Name,PremiumAmount__c,Due_Date__c FROM Life_Insurence__c where Policy_Holder__c=:data ];

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    //----------------------------------------------------------------------------
    @AuraEnabled(cacheable=true)
    public static List<Motor_Insurence__c> MotorData(id data){
        try {
            return [select Name,Premium_Amount__c,Due_Date__c FROM Motor_Insurence__c where Policy_Holder__c=:data ];

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}
    
    


    
   